#!/bin/python

import argparse
import time
import classes


def args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--config',
                        default='conf.yaml')
    parser.add_argument('-f', '--file',
                        defaults='txt.yaml')
    (options, args) = parser.parse_args
    options = vars(options)

    try:
        num = int(args[0])
    except:
        num = 1000

    gids = db.getgids(num)
    with open (options['config'], 'r') as f:
        stats = yaml.load(f)

    for s in stats:
        sp = classes.StatPlot(s, gids, outfile=options['file'])
        sp.execute()

if __name__ == "__main__":
    args()
